/* Build both halves of the MCP server:
   · dist/server.mjs  — Node stdio MCP server (playwright-core external)
   · dist/harness.js  — browser bundle of the repo's real render/export
     engine (src/lib/motion/*), loaded by headless Chromium
   · dist/harness.html — copied from src/harness */
import { build } from 'esbuild';
import { mkdirSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
mkdirSync(join(here, 'dist'), { recursive: true });

await build({
  entryPoints: [join(here, 'src/server.ts')],
  outfile: join(here, 'dist/server.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  // Keep runtime deps external — they live in node_modules next to dist.
  external: ['playwright-core', '@modelcontextprotocol/sdk', 'zod', '@ffmpeg-installer/ffmpeg'],
  banner: { js: '// Generated by build.mjs — do not edit.' },
});

await build({
  entryPoints: [join(here, 'src/harness/harness.ts')],
  outfile: join(here, 'dist/harness.js'),
  bundle: true,
  platform: 'browser',
  format: 'iife',
  target: 'chrome110',
  banner: { js: '// Generated by build.mjs — do not edit.' },
});

copyFileSync(join(here, 'src/harness/harness.html'), join(here, 'dist/harness.html'));
console.log('build ok: dist/server.mjs, dist/harness.js, dist/harness.html');
