/**
 * Diagnosis engine — turns parser output + read-only Neoserra findings into
 * a plain-English verdict and a copy-pasteable, email-ready explanation.
 *
 * Pure functions — no I/O. Honesty rule: when we can't verify something
 * (e.g. the API key can't read milestone records), say so plainly and point
 * at the manual check (Neoserra's API Audit Trail) instead of guessing.
 */

import type {
  Diagnosis,
  EmailDraft,
  NeoserraFindings,
  ParsedSubmission,
  VerdictStatus,
} from './types';
import { endpointReadable } from './neoserra-read';

const AUDIT_TRAIL_HINT =
  'System Administration → API Audit Trail in Neoserra shows every payload the API received and whether it was processed — it is the ground truth for whether the write arrived.';

function toolLink(p: { businessId?: string | null; email?: string | null }): string {
  const base = 'https://tools.norcalsbdc.org/api-troubleshooter';
  if (p.businessId) return `${base}?business=${encodeURIComponent(p.businessId)}`;
  if (p.email) return `${base}?email=${encodeURIComponent(p.email)}`;
  return base;
}

function clientLink(businessId: string | null): string | null {
  return businessId ? `https://norcal.neoserra.com/clients/${businessId}` : null;
}

function submissionSummary(p: ParsedSubmission): string {
  const lines: string[] = [];
  if (p.milestoneTypes.length) lines.push(`Milestones claimed: ${p.milestoneTypes.join('; ')}`);
  for (const f of p.fields) {
    if (['Contact ID', 'Contact Email', 'Contact First Name', 'Select Business', 'Select all that apply'].includes(f.label)) continue;
    if (f.value) lines.push(`${f.label}: ${f.value}`);
  }
  if (p.contactId || p.businessId) {
    lines.push(`Contact ${p.contactId ?? '—'} · Business ${p.businessId ?? '—'}`);
  }
  return lines.join('\n');
}

function anomalyParagraph(p: ParsedSubmission): string {
  if (!p.anomalies.length) return '';
  const items = p.anomalies
    .map((a) => `- ${a.field}: ${a.issue}${a.suggestion ? ` ${a.suggestion}` : ''}`)
    .join('\n');
  return `\nValues worth double-checking:\n${items}\n`;
}

function draft(subject: string, paragraphs: string[], link: string): EmailDraft {
  const body = [
    'Hi —',
    ...paragraphs.filter(Boolean),
    `This summary was generated by the API Troubleshooter: ${link}`,
  ].join('\n\n');
  return { subject, body };
}

/** Build the diagnosis for the paste-a-notification flow. */
export function diagnoseSubmission(p: ParsedSubmission, neo: NeoserraFindings): Diagnosis {
  const who = [p.firstName, p.signature].filter(Boolean)[0] || p.contactEmail || 'The client';
  const biz = p.businessId ?? 'unknown';
  const link = toolLink({ businessId: p.businessId, email: p.contactEmail });
  const neoClient = clientLink(p.businessId);
  const dataBlock = `Their submission (no need to ask the client to resubmit — we have their complete answers):\n${submissionSummary(p)}`;
  const anomalies = anomalyParagraph(p);

  // ── Not configured: parser-only mode ──
  if (!neo.configured) {
    return finish('not-configured', 'Parsed — Neoserra check unavailable', {
      whatHappened: `The notification email parsed cleanly: ${who} submitted the milestone form (business ${biz}). The submission reached WordPress and the notification went out.`,
      likelyIssue:
        'This deployment has no Neoserra API credentials, so the troubleshooter could not check whether a matching record exists in Neoserra.' +
        (p.anomalies.length ? ' Separately, some submitted values look wrong — see below.' : ''),
      fix: `Check manually: ${AUDIT_TRAIL_HINT}${neoClient ? ` Client record: ${neoClient}` : ''}`,
    });
  }

  const milestonesReadable = neo.milestones ? endpointReadable(neo.milestones) : false;
  const found = neo.milestones?.found ?? false;

  // ── Delivered ──
  if (found) {
    return finish(p.anomalies.length ? 'value-anomaly' : 'delivered',
      p.anomalies.length ? 'Delivered, but values look wrong' : 'Delivered to Neoserra', {
      whatHappened: `${who} submitted the milestone form for business ${biz}, and Neoserra has milestone record(s) for that client — the handoff worked.`,
      likelyIssue: p.anomalies.length
        ? 'The record made it to Neoserra, but some submitted values look wrong (see below) — the EI numbers may misstate the client’s actual progress.'
        : 'No issue detected. If an advisor reports it missing, the record may be sitting in the milestone approval queue or scoped to a different center, or only the advisor notification email failed to arrive.',
      fix: p.anomalies.length
        ? `Review the record in Neoserra${neoClient ? ` (${neoClient})` : ''} and correct the flagged values after confirming with the advisor.`
        : `If someone can’t see it: check the milestone approval queue and the record’s center assignment${neoClient ? ` (${neoClient})` : ''}. If they simply never got an email, have them check spam for mail from norcalsbdc.org.`,
    });
  }

  // ── Readable but no record → missing ──
  if (milestonesReadable) {
    return finish('missing', 'Not found in Neoserra', {
      whatHappened: `${who} submitted the milestone form and the submission was captured (business ${biz}) — but Neoserra has no matching milestone record for that client.`,
      likelyIssue:
        'The handoff between the website form and Neoserra failed for this submission. Neoserra sometimes rejects or silently drops records it doesn’t like' +
        (p.anomalies.length ? ' — and some values in this submission look like the kind Neoserra chokes on (see below).' : '.'),
      fix: `(1) ${AUDIT_TRAIL_HINT} Look near the submission time. (2) If nothing arrived or it shows an error, enter the milestone manually from the data below${neoClient ? ` on ${neoClient}` : ''}. (3) If this keeps happening, the website form’s Neoserra connection needs attention.`,
    });
  }

  // ── Could not read milestones at all → honest unverifiable ──
  return finish('unverifiable', 'Captured — Neoserra status needs a manual check', {
    whatHappened: `${who} submitted the milestone form and the submission was captured in full (business ${biz}).`,
    likelyIssue:
      'The troubleshooter’s API key cannot read milestone records from Neoserra (the read endpoints answered ' +
      summarizeAttempts(neo) +
      '), so it can’t confirm whether the record was written.' +
      (p.anomalies.length ? ' Some submitted values also look wrong — see below.' : ''),
    fix: `Check manually: ${AUDIT_TRAIL_HINT} Look near the submission time${neoClient ? `, and check ${neoClient} for the milestone` : ''}. If it’s not there, enter it manually from the data below.`,
  });

  function finish(
    status: VerdictStatus,
    headline: string,
    text: { whatHappened: string; likelyIssue: string; fix: string },
  ): Diagnosis {
    const subject = `Milestone submission for business ${biz}${p.signature ? ` (${p.signature})` : ''} — status and next step`;
    return {
      status,
      headline,
      ...text,
      emailDraft: draft(
        subject,
        [
          `We looked into a milestone (EI) submission and here’s what we found:`,
          `What happened: ${text.whatHappened}`,
          `Likely issue: ${text.likelyIssue}`,
          `The fix: ${text.fix}`,
          anomalies.trim(),
          dataBlock,
        ],
        link,
      ),
    };
  }
}

/** Build the diagnosis for the look-up-a-client flow (no pasted email). */
export function diagnoseLookup(
  query: { email?: string; businessId?: string; contactId?: string },
  neo: NeoserraFindings,
): Diagnosis {
  const label = query.email || `business ${query.businessId}` || `contact ${query.contactId}`;
  const link = toolLink({ businessId: query.businessId ?? null, email: query.email ?? null });
  const neoClient = clientLink(query.businessId ?? null);

  if (!neo.configured) {
    return {
      status: 'not-configured',
      headline: 'Neoserra check unavailable',
      whatHappened: `Looked up ${label}.`,
      likelyIssue: 'This deployment has no Neoserra API credentials, so no live check was possible.',
      fix: 'Set NEOSERRA_BASE_URL and NEOSERRA_API_KEY (read access) on the deployment, or check the record directly in Neoserra.',
      emailDraft: draft(`Neoserra check for ${label}`, ['The troubleshooter is not connected to Neoserra on this deployment, so no live check was possible.'], link),
    };
  }

  const contactFound = neo.contact?.found ?? false;
  const clientFound = neo.client?.found ?? false;
  const milestonesFound = neo.milestones?.found ?? false;
  const milestonesReadable = neo.milestones ? endpointReadable(neo.milestones) : false;

  // Email lookup that found nothing → the classic "email is not valid" case.
  if (query.email && !contactFound && neo.contact && endpointReadable(neo.contact)) {
    return {
      status: 'lookup-failed',
      headline: 'No Neoserra contact has this exact email',
      whatHappened: `Searched Neoserra for a contact with the email ${query.email} — no match.`,
      likelyIssue:
        'This is why the milestone form tells this client their "email is not valid": the form finds clients by exact email match. The client’s contact record probably has a different address — a typo, an old email, or the email may be on the client record but not the contact record.',
      fix: `Open the client’s record in Neoserra and compare the CONTACT record’s email (not just the client record) character-by-character with ${query.email} — watch for extra spaces, dots, or an alias. Fix the contact email (or tell the client which address to use) and have them try the form again.`,
      emailDraft: draft(
        `Milestone form lookup for ${query.email} — why it fails and the fix`,
        [
          `A client can’t get past the milestone form’s email step with ${query.email}. We checked Neoserra directly:`,
          `What happened: No contact record in Neoserra has that exact email address, and the form matches on exact email — so it reports the email as not valid.`,
          `The fix: Compare the contact record’s email in Neoserra with the address the client is typing (watch for typos, old addresses, or the email living on the client record instead of the contact record). Align the two, then have the client retry.`,
        ],
        link,
      ),
    };
  }

  const linkedIds = neo.linkedClientIds ?? [];
  const parts: string[] = [];
  if (query.email) parts.push(contactFound ? `Contact found for ${query.email}.` : `Contact lookup was inconclusive (endpoint ${neo.contact ? summarizeResult(neo.contact.attempts.map((a) => a.status)) : 'not tried'}).`);
  if (query.businessId) parts.push(clientFound ? `Client ${query.businessId} exists in Neoserra.` : `Client ${query.businessId} was not readable.`);
  if (!query.businessId && contactFound) {
    parts.push(
      linkedIds.length
        ? `Linked client record(s) on the contact: ${linkedIds.join(', ')}.`
        : 'No linked client records could be identified from the contact data (see technical details for the raw record).',
    );
  }
  parts.push(
    milestonesFound
      ? 'Milestone record(s) found for this client.'
      : milestonesReadable
        ? 'The milestone endpoint answered, but returned no records for this client.'
        : 'Milestone records could not be read with this API key.',
  );

  const clientLinks = (query.businessId ? [query.businessId] : linkedIds)
    .map((id) => `https://norcal.neoserra.com/clients/${id}`)
    .join(' · ');

  const status: VerdictStatus = milestonesFound ? 'lookup-ok' : milestonesReadable ? 'missing' : 'unverifiable';
  return {
    status,
    headline: milestonesFound
      ? 'Client and milestone records found'
      : milestonesReadable
        ? 'Client found — no milestone records'
        : contactFound || clientFound
          ? 'Found in Neoserra — milestone status needs a manual check'
          : 'Lookup inconclusive',
    whatHappened: parts.join(' '),
    likelyIssue: milestonesFound
      ? 'No issue detected at the Neoserra end. If an advisor can’t see the milestone, check the approval queue, the center assignment, or their notification email (spam filtering).'
      : milestonesReadable
        ? 'If this client says they submitted the form, the record never made it to Neoserra — paste their notification email into this tool for a full trace, or check the API Audit Trail near the submission time.'
        : `The lookup side works (that’s what the milestone form needs), but this API key can’t read milestone records back, so delivery can’t be confirmed from here. ${AUDIT_TRAIL_HINT}`,
    fix: clientLinks
      ? `Open the client record${linkedIds.length > 1 ? 's' : ''}: ${clientLinks} — check the milestone list and the approval queue there. To trace a specific submission, paste its notification email into this tool.`
      : neoClient
        ? `Client record: ${neoClient}`
        : 'Search the client in Neoserra to continue, or paste the submission’s notification email here for a full trace.',
    emailDraft: draft(
      `Neoserra check for ${label}`,
      [
        `We ran a live Neoserra check for ${label}:`,
        parts.join(' '),
        milestonesFound
          ? 'If the milestone isn’t visible to you, check the milestone approval queue and the record’s center assignment — and check your spam folder for the notification email.'
          : 'If this client submitted the milestone form, the record may not have reached Neoserra — we can trace the exact submission from the notification email.',
        clientLinks ? `Client record${linkedIds.length > 1 ? 's' : ''}: ${clientLinks}` : '',
      ],
      link,
    ),
  };
}

function summarizeResult(statuses: (number | string)[]): string {
  return statuses.map(String).join(', ');
}

function summarizeAttempts(neo: NeoserraFindings): string {
  const s = neo.milestones?.attempts.map((a) => `${a.status}`) ?? [];
  return s.length ? s.join('/') : 'no attempts';
}
