'use client';

import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

/* ═══════════════════════════════════════════════════════
   Milestones — Internationalization
   Supported: en, es, vi, zh, fr
   ═══════════════════════════════════════════════════════ */

export type Locale = 'en' | 'es' | 'vi' | 'zh' | 'fr';

export const LOCALES: { code: Locale; flag: string; label: string }[] = [
  { code: 'en', flag: '🇺🇸', label: 'English' },
  { code: 'es', flag: '🇪🇸', label: 'Español' },
  { code: 'vi', flag: '🇻🇳', label: 'Tiếng Việt' },
  { code: 'zh', flag: '🇨🇳', label: '中文' },
  { code: 'fr', flag: '🇫🇷', label: 'Français' },
];

// ─── Translation dictionary ─────────────────────────────

const T: Record<string, Record<Locale, string>> = {
  // ── Navigation ──
  'nav.continue': { en: 'Continue', es: 'Continuar', vi: 'Tiếp tục', zh: '继续', fr: 'Continuer' },
  'nav.back': { en: 'Back', es: 'Atrás', vi: 'Quay lại', zh: '返回', fr: 'Retour' },
  'nav.submit': { en: 'Submit', es: 'Enviar', vi: 'Gửi', zh: '提交', fr: 'Soumettre' },
  'nav.searching': { en: 'Searching...', es: 'Buscando...', vi: 'Đang tìm...', zh: '搜索中...', fr: 'Recherche...' },
  'nav.yes': { en: 'Yes', es: 'Sí', vi: 'Có', zh: '是', fr: 'Oui' },
  'nav.no': { en: 'No', es: 'No', vi: 'Không', zh: '否', fr: 'Non' },

  // ── Contact Lookup ──
  'contact.title': { en: 'Share Your Business Impact', es: 'Comparta el impacto de su negocio', vi: 'Chia sẻ tác động kinh doanh', zh: '分享您的业务影响', fr: 'Partagez l\u2019impact de votre entreprise' },
  'contact.subtitle': { en: 'To get started, please provide your contact information so we can retrieve your client record.', es: 'Para comenzar, proporcione su información de contacto para que podamos recuperar su registro de cliente.', vi: 'Để bắt đầu, vui lòng cung cấp thông tin liên hệ để chúng tôi truy xuất hồ sơ khách hàng.', zh: '首先，请提供您的联系信息，以便我们检索您的客户记录。', fr: 'Pour commencer, veuillez fournir vos coordonnées afin que nous puissions récupérer votre dossier client.' },
  'contact.whyLink': { en: 'Why does this matter?', es: '¿Por qué es importante?', vi: 'Tại sao điều này quan trọng?', zh: '为什么这很重要？', fr: 'Pourquoi est-ce important ?' },
  'contact.firstName': { en: 'First Name', es: 'Nombre', vi: 'Tên', zh: '名', fr: 'Prénom' },
  'contact.lastName': { en: 'Last Name', es: 'Apellido', vi: 'Họ', zh: '姓', fr: 'Nom' },
  'contact.email': { en: 'Email', es: 'Correo electrónico', vi: 'Email', zh: '电子邮件', fr: 'E-mail' },
  'contact.phone': { en: 'Phone', es: 'Teléfono', vi: 'Điện thoại', zh: '电话', fr: 'Téléphone' },
  'contact.loading': { en: 'Looking up your records...', es: 'Buscando sus registros...', vi: 'Đang tìm hồ sơ của bạn...', zh: '正在查找您的记录...', fr: 'Recherche de vos dossiers...' },
  'contact.notFound': { en: 'No contact records found in our system with the email address provided. Please verify your email or contact your local SBDC for assistance.', es: 'No se encontraron registros con la dirección de correo proporcionada. Verifique su correo o contacte a su SBDC local.', vi: 'Không tìm thấy hồ sơ liên hệ với địa chỉ email đã cung cấp. Vui lòng xác minh email hoặc liên hệ SBDC địa phương.', zh: '未找到与所提供电子邮件地址匹配的联系记录。请验证您的电子邮件或联系当地SBDC寻求帮助。', fr: 'Aucun dossier trouvé avec l\u2019adresse e-mail fournie. Veuillez vérifier votre e-mail ou contacter votre SBDC local.' },
  'contact.error': { en: 'Failed to look up contact. Please try again.', es: 'Error al buscar el contacto. Intente de nuevo.', vi: 'Không thể tra cứu liên hệ. Vui lòng thử lại.', zh: '查找联系人失败。请重试。', fr: 'Échec de la recherche. Veuillez réessayer.' },

  // ── Why Modal ──
  'why.title': { en: 'Your Feedback Matters', es: 'Su opinión importa', vi: 'Phản hồi của bạn rất quan trọng', zh: '您的反馈很重要', fr: 'Votre avis compte' },
  'why.intro': { en: 'Your milestones are more than just numbers \u2014 they are powerful stories of resilience, growth, and success. By sharing your achievements, you not only celebrate your own triumphs but also contribute to the success of fellow small business owners.', es: 'Sus logros son más que números \u2014 son historias poderosas de resiliencia, crecimiento y éxito. Al compartir sus logros, no solo celebra sus propios triunfos sino que contribuye al éxito de otros propietarios de pequeñas empresas.', vi: 'Các cột mốc của bạn không chỉ là con số \u2014 chúng là những câu chuyện mạnh mẽ về sự kiên cường, tăng trưởng và thành công. Bằng cách chia sẻ thành tựu, bạn không chỉ tôn vinh chiến thắng của mình mà còn góp phần vào thành công của các chủ doanh nghiệp nhỏ khác.', zh: '您的里程碑不仅仅是数字——它们是关于韧性、成长和成功的有力故事。通过分享您的成就，您不仅庆祝自己的胜利，还为其他小企业主的成功做出贡献。', fr: 'Vos jalons sont bien plus que des chiffres \u2014 ce sont des histoires puissantes de résilience, de croissance et de succès. En partageant vos réalisations, vous célébrez vos propres triomphes et contribuez au succès d\u2019autres entrepreneurs.' },
  'why.howHeader': { en: 'Here\u2019s how your feedback makes a difference:', es: 'Así es como su opinión marca la diferencia:', vi: 'Đây là cách phản hồi của bạn tạo ra sự khác biệt:', zh: '以下是您的反馈如何产生影响：', fr: 'Voici comment vos retours font la différence :' },
  'why.impact': { en: 'Demonstrating Impact', es: 'Demostrar impacto', vi: 'Thể hiện tác động', zh: '展示影响力', fr: 'Démontrer l\u2019impact' },
  'why.impactDesc': { en: 'Your successes help us showcase the tangible impact of our services, proving that our support truly makes a difference in the lives of entrepreneurs like you.', es: 'Sus éxitos nos ayudan a mostrar el impacto tangible de nuestros servicios, demostrando que nuestro apoyo realmente marca la diferencia.', vi: 'Thành công của bạn giúp chúng tôi thể hiện tác động thực tế của dịch vụ, chứng minh rằng sự hỗ trợ thực sự tạo ra sự khác biệt.', zh: '您的成功帮助我们展示服务的切实影响，证明我们的支持确实改变了像您这样的企业家的生活。', fr: 'Vos succès nous aident à montrer l\u2019impact tangible de nos services.' },
  'why.resources': { en: 'Securing Resources', es: 'Asegurar recursos', vi: 'Đảm bảo nguồn lực', zh: '确保资源', fr: 'Sécuriser les ressources' },
  'why.resourcesDesc': { en: 'By highlighting the collective achievements of our clients, we can secure critical funding and resources to continue providing high-quality support and expand our reach to even more small businesses in need.', es: 'Al destacar los logros colectivos de nuestros clientes, podemos asegurar financiamiento y recursos críticos para continuar brindando apoyo de alta calidad.', vi: 'Bằng cách nêu bật thành tựu chung của khách hàng, chúng tôi có thể đảm bảo nguồn tài trợ và tài nguyên quan trọng để tiếp tục hỗ trợ.', zh: '通过突出客户的集体成就，我们可以确保关键资金和资源，继续提供高质量支持。', fr: 'En mettant en avant les réalisations collectives, nous pouvons sécuriser des financements essentiels pour continuer notre soutien.' },
  'why.inspiring': { en: 'Inspiring Others', es: 'Inspirar a otros', vi: 'Truyền cảm hứng', zh: '激励他人', fr: 'Inspirer les autres' },
  'why.inspiringDesc': { en: 'Your stories of overcoming challenges and reaching new heights serve as inspiration for other entrepreneurs who are just starting out or facing similar obstacles.', es: 'Sus historias de superación sirven de inspiración para otros emprendedores que están comenzando o enfrentan obstáculos similares.', vi: 'Những câu chuyện vượt qua thử thách của bạn là nguồn cảm hứng cho các doanh nhân khác đang bắt đầu hoặc đối mặt với trở ngại tương tự.', zh: '您克服挑战的故事为刚起步或面临类似困难的其他企业家提供了灵感。', fr: 'Vos histoires de réussite inspirent d\u2019autres entrepreneurs qui débutent ou font face à des défis similaires.' },
  'why.shaping': { en: 'Shaping Our Services', es: 'Mejorar nuestros servicios', vi: 'Định hình dịch vụ', zh: '完善我们的服务', fr: 'Améliorer nos services' },
  'why.shapingDesc': { en: 'Your feedback helps us better understand your needs and tailor our services to provide the most effective support possible.', es: 'Su opinión nos ayuda a entender mejor sus necesidades y adaptar nuestros servicios.', vi: 'Phản hồi giúp chúng tôi hiểu rõ hơn nhu cầu của bạn và điều chỉnh dịch vụ.', zh: '您的反馈帮助我们更好地了解您的需求并调整服务。', fr: 'Vos retours nous aident à mieux comprendre vos besoins et adapter nos services.' },
  'why.closing': { en: 'Don\u2019t underestimate the power of your voice. Together, we can create a ripple effect of success that strengthens our local economy and builds a brighter future for all.', es: 'No subestime el poder de su voz. Juntos, podemos crear un efecto dominó de éxito que fortalezca nuestra economía local.', vi: 'Đừng đánh giá thấp sức mạnh giọng nói của bạn. Cùng nhau, chúng ta có thể tạo ra hiệu ứng lan tỏa thành công.', zh: '不要低估您声音的力量。我们可以共同创造成功的连锁效应，增强当地经济。', fr: 'Ne sous-estimez pas le pouvoir de votre voix. Ensemble, nous pouvons créer un effet d\u2019entraînement qui renforce notre économie locale.' },

  // ── Select Business ──
  'biz.title': { en: 'Select Your Business', es: 'Seleccione su negocio', vi: 'Chọn doanh nghiệp', zh: '选择您的企业', fr: 'Sélectionnez votre entreprise' },
  'biz.subtitle': { en: 'We found the following business record(s) associated with your account. Please select the business you\u2019d like to report milestones for.', es: 'Encontramos los siguientes registros asociados a su cuenta. Seleccione el negocio para el que desea reportar logros.', vi: 'Chúng tôi tìm thấy các hồ sơ doanh nghiệp liên kết với tài khoản của bạn. Vui lòng chọn doanh nghiệp bạn muốn báo cáo.', zh: '我们找到了与您帐户关联的企业记录。请选择您要报告里程碑的企业。', fr: 'Nous avons trouvé les dossiers suivants associés à votre compte. Veuillez sélectionner l\u2019entreprise concernée.' },

  // ── Select Milestones ──
  'select.title': { en: 'How has SBDC supported your business?', es: '¿Cómo ha apoyado el SBDC a su negocio?', vi: 'SBDC đã hỗ trợ doanh nghiệp của bạn như thế nào?', zh: 'SBDC如何支持了您的企业？', fr: 'Comment le SBDC a-t-il soutenu votre entreprise ?' },
  'select.subtitle': { en: 'Select the area(s) corresponding to how SBDC has supported your business.', es: 'Seleccione las áreas correspondientes al apoyo del SBDC.', vi: 'Chọn các lĩnh vực tương ứng với sự hỗ trợ của SBDC.', zh: '选择SBDC支持您企业的相应领域。', fr: 'Sélectionnez les domaines correspondant au soutien du SBDC.' },
  'select.hired': { en: 'I Hired New Employees', es: 'Contraté nuevos empleados', vi: 'Tôi đã tuyển nhân viên mới', zh: '我雇用了新员工', fr: 'J\u2019ai embauché de nouveaux employés' },
  'select.hiredDesc': { en: 'You added full-time or part-time staff since working with SBDC. Include yourself if you started a new business.', es: 'Agregó personal de tiempo completo o parcial desde que trabaja con el SBDC. Inclúyase si inició un negocio.', vi: 'Bạn đã thêm nhân viên toàn thời gian hoặc bán thời gian. Bao gồm bản thân nếu bạn bắt đầu kinh doanh mới.', zh: '您自与SBDC合作以来增加了全职或兼职员工。如果您创办了新企业，请包括您自己。', fr: 'Vous avez ajouté du personnel depuis votre collaboration avec le SBDC. Incluez-vous si vous avez créé une entreprise.' },
  'select.sales': { en: 'I Increased My Sales', es: 'Aumenté mis ventas', vi: 'Tôi đã tăng doanh số', zh: '我增加了销售额', fr: 'J\u2019ai augmenté mes ventes' },
  'select.salesDesc': { en: 'Your gross revenue grew compared to what was previously reported. You\u2019ll enter last year\u2019s total from your tax return.', es: 'Sus ingresos brutos crecieron comparados con lo reportado anteriormente. Ingresará el total del año pasado de su declaración de impuestos.', vi: 'Doanh thu gộp của bạn tăng so với lần báo cáo trước. Bạn sẽ nhập tổng năm ngoái từ khai thuế.', zh: '您的总收入与之前报告的相比有所增长。您将输入去年纳税申报表上的总额。', fr: 'Votre chiffre d\u2019affaires a augmenté. Vous saisirez le total de l\u2019année dernière de votre déclaration fiscale.' },
  'select.started': { en: 'I Started a New Business', es: 'Inicié un nuevo negocio', vi: 'Tôi đã bắt đầu kinh doanh mới', zh: '我创办了新企业', fr: 'J\u2019ai créé une nouvelle entreprise' },
  'select.startedDesc': { en: 'You registered a new business and began operations \u2014 selling products/services, hiring, or investing capital.', es: 'Registró un nuevo negocio y comenzó operaciones \u2014 vendiendo productos/servicios, contratando o invirtiendo capital.', vi: 'Bạn đã đăng ký doanh nghiệp mới và bắt đầu hoạt động \u2014 bán sản phẩm/dịch vụ, tuyển dụng hoặc đầu tư vốn.', zh: '您注册了新企业并开始运营——销售产品/服务、招聘或投资资本。', fr: 'Vous avez enregistré une nouvelle entreprise et commencé vos opérations.' },
  'select.funded': { en: 'I Got My Business Funded', es: 'Obtuve financiamiento', vi: 'Tôi đã được cấp vốn', zh: '我获得了企业融资', fr: 'J\u2019ai obtenu un financement' },
  'select.fundedDesc': { en: 'You secured capital such as owner investment, bank loans, SBA loans, grants, or other funding sources.', es: 'Obtuvo capital como inversión propia, préstamos bancarios, préstamos SBA, subvenciones u otras fuentes.', vi: 'Bạn đã có được vốn như đầu tư chủ sở hữu, vay ngân hàng, vay SBA, tài trợ hoặc nguồn khác.', zh: '您获得了资本，如业主投资、银行贷款、SBA贷款、赠款或其他资金来源。', fr: 'Vous avez obtenu du capital : investissement personnel, prêts bancaires, prêts SBA, subventions, etc.' },
  'select.checkpoint': { en: 'Business Growth Checkpoint:', es: 'Punto de control de crecimiento:', vi: 'Điểm kiểm tra tăng trưởng:', zh: '业务增长检查点：', fr: 'Point de contrôle de croissance :' },
  'select.checkHired': { en: 'Hiring new employees is a significant step. Did this coincide with starting a new business, receiving funding, or increasing your sales? If applicable, please select those options too.', es: 'Contratar empleados es un paso significativo. ¿Coincidió con iniciar un negocio, recibir financiamiento o aumentar ventas? Si aplica, seleccione esas opciones también.', vi: 'Tuyển nhân viên mới là bước quan trọng. Điều này có trùng với việc bắt đầu kinh doanh mới, nhận tài trợ hoặc tăng doanh số không? Nếu có, hãy chọn thêm.', zh: '雇用新员工是重要的一步。这是否与创办新企业、获得资金或增加销售同时发生？如果适用，请也选择这些选项。', fr: 'L\u2019embauche est une étape importante. Cela a-t-il coïncidé avec la création d\u2019entreprise, un financement ou une augmentation des ventes ?' },
  'select.checkSales': { en: 'Great job increasing your sales! Did this growth allow you to hire new employees or get additional funding? Or perhaps this is for a newly started business? Please select any other applicable options.', es: '¡Excelente aumento de ventas! ¿Este crecimiento le permitió contratar empleados u obtener financiamiento adicional? Seleccione otras opciones aplicables.', vi: 'Tuyệt vời khi tăng doanh số! Sự tăng trưởng này có cho phép bạn tuyển nhân viên hoặc nhận thêm tài trợ không? Hãy chọn thêm nếu có.', zh: '销售增长做得好！这种增长是否让您招聘了新员工或获得了额外资金？请选择其他适用选项。', fr: 'Bravo pour l\u2019augmentation des ventes ! Cela vous a-t-il permis d\u2019embaucher ou d\u2019obtenir des financements supplémentaires ?' },
  'select.checkStarted': { en: 'Starting a new business often involves other milestones. Have you also hired employees (including yourself), received funding, or increased sales? If so, please select those options as well.', es: 'Iniciar un negocio a menudo implica otros logros. ¿También contrató empleados (incluido usted), recibió financiamiento o aumentó ventas? Si es así, seleccione esas opciones.', vi: 'Bắt đầu kinh doanh mới thường liên quan đến các cột mốc khác. Bạn cũng đã tuyển nhân viên, nhận tài trợ hoặc tăng doanh số chưa? Nếu có, hãy chọn thêm.', zh: '创办新企业通常涉及其他里程碑。您是否也雇用了员工（包括您自己）、获得了资金或增加了销售？如果是，请也选择这些选项。', fr: 'Créer une entreprise implique souvent d\u2019autres jalons. Avez-vous aussi embauché, obtenu des fonds ou augmenté vos ventes ?' },
  'select.checkFunded': { en: 'Congratulations on receiving funding! Did this funding help you start a new business, hire employees, or increase sales? If so, consider selecting those options as well.', es: '¡Felicitaciones por recibir financiamiento! ¿Este financiamiento le ayudó a iniciar un negocio, contratar empleados o aumentar ventas? Considere seleccionar esas opciones.', vi: 'Chúc mừng đã nhận được tài trợ! Tài trợ này có giúp bạn bắt đầu kinh doanh mới, tuyển nhân viên hoặc tăng doanh số không? Hãy cân nhắc chọn thêm.', zh: '恭喜获得融资！这笔资金是否帮助您创办新企业、雇用员工或增加销售？如果是，请考虑也选择这些选项。', fr: 'Félicitations pour le financement ! Cela vous a-t-il aidé à créer une entreprise, embaucher ou augmenter vos ventes ?' },

  // ── Employees Step ──
  'emp.title': { en: 'Hired New Employees', es: 'Contratación de nuevos empleados', vi: 'Tuyển nhân viên mới', zh: '雇用新员工', fr: 'Nouveaux employés embauchés' },
  'emp.desc': { en: 'Please enter the total number of current full-time and part-time employees for your business. Don\u2019t forget to include yourself in the employee count if you\u2019re updating a new business.', es: 'Ingrese el número total de empleados actuales de tiempo completo y parcial. No olvide incluirse si está actualizando un negocio nuevo.', vi: 'Vui lòng nhập tổng số nhân viên toàn thời gian và bán thời gian hiện tại. Đừng quên bao gồm bản thân nếu bạn đang cập nhật doanh nghiệp mới.', zh: '请输入您企业当前全职和兼职员工的总数。如果您在更新新企业，别忘了将自己包括在内。', fr: 'Veuillez saisir le nombre total d\u2019employés actuels à temps plein et partiel. N\u2019oubliez pas de vous inclure si vous mettez à jour une nouvelle entreprise.' },
  'emp.trackingNote': { en: 'This helps SBDC track the job creation impact of our services.', es: 'Esto ayuda al SBDC a rastrear el impacto de creación de empleo.', vi: 'Điều này giúp SBDC theo dõi tác động tạo việc làm.', zh: '这帮助SBDC追踪我们服务的就业创造影响。', fr: 'Cela aide le SBDC à suivre l\u2019impact en matière de création d\u2019emplois.' },
  'emp.ftLabel': { en: 'Total Full-Time Employees', es: 'Total de empleados tiempo completo', vi: 'Tổng nhân viên toàn thời gian', zh: '全职员工总数', fr: 'Total employés à temps plein' },
  'emp.ptLabel': { en: 'Total Part-Time Employees', es: 'Total de empleados tiempo parcial', vi: 'Tổng nhân viên bán thời gian', zh: '兼职员工总数', fr: 'Total employés à temps partiel' },
  'emp.prevReported': { en: 'Previously reported:', es: 'Reportado anteriormente:', vi: 'Đã báo cáo trước đó:', zh: '之前报告的：', fr: 'Précédemment déclaré :' },
  'emp.ftHint': { en: 'Be sure to include yourself as an employee.', es: 'Asegúrese de incluirse como empleado.', vi: 'Hãy nhớ bao gồm bản thân là nhân viên.', zh: '请确保将自己包括在内。', fr: 'N\u2019oubliez pas de vous compter comme employé.' },
  'emp.ptHint': { en: 'Include yourself if you work part-time and did not already count yourself as full-time.', es: 'Inclúyase si trabaja a tiempo parcial y no se contó como tiempo completo.', vi: 'Bao gồm bản thân nếu bạn làm bán thời gian và chưa tính là toàn thời gian.', zh: '如果您是兼职且未计为全职，请将自己包括在内。', fr: 'Incluez-vous si vous travaillez à temps partiel et ne vous êtes pas déjà compté à temps plein.' },
  'emp.ftDelta': { en: 'full-time', es: 'tiempo completo', vi: 'toàn thời gian', zh: '全职', fr: 'temps plein' },
  'emp.ptDelta': { en: 'part-time', es: 'tiempo parcial', vi: 'bán thời gian', zh: '兼职', fr: 'temps partiel' },

  // ── Sales Step ──
  'sales.title': { en: 'Sales / Gross Revenue', es: 'Ventas / Ingresos brutos', vi: 'Doanh số / Doanh thu gộp', zh: '销售/总收入', fr: 'Ventes / Chiffre d\u2019affaires' },
  'sales.desc': { en: 'Enter your business\u2019s gross revenue for the most recent fiscal year. You can find this on your tax forms.', es: 'Ingrese los ingresos brutos de su negocio del año fiscal más reciente. Puede encontrarlo en sus formularios de impuestos.', vi: 'Nhập doanh thu gộp của doanh nghiệp cho năm tài chính gần nhất. Bạn có thể tìm thấy trên biểu mẫu thuế.', zh: '输入您企业最近财政年度的总收入。您可以在纳税表上找到。', fr: 'Saisissez le chiffre d\u2019affaires brut de votre dernière année fiscale. Vous le trouverez sur vos formulaires fiscaux.' },
  'sales.label': { en: 'Last Year\u2019s Gross Revenue', es: 'Ingresos brutos del año pasado', vi: 'Doanh thu gộp năm ngoái', zh: '去年总收入', fr: 'Chiffre d\u2019affaires de l\u2019année dernière' },
  'sales.hint': { en: 'This can typically be found on your business tax return: Form 1120 (C Corp) Line 1a, Form 1120S (S Corp) Line 1a, Form 1065 (Partnership) Line 1a, or Schedule C (Sole Prop) Line 1.', es: 'Esto se encuentra típicamente en su declaración de impuestos: Formulario 1120 Línea 1a, Formulario 1120S Línea 1a, Formulario 1065 Línea 1a, o Anexo C Línea 1.', vi: 'Thường có thể tìm thấy trên khai thuế: Mẫu 1120 Dòng 1a, Mẫu 1120S Dòng 1a, Mẫu 1065 Dòng 1a, hoặc Bảng C Dòng 1.', zh: '通常可以在您的企业纳税申报表上找到：表格1120第1a行、表格1120S第1a行、表格1065第1a行或附表C第1行。', fr: 'Se trouve généralement sur votre déclaration fiscale : Formulaire 1120 Ligne 1a, 1120S Ligne 1a, 1065 Ligne 1a, ou Annexe C Ligne 1.' },
  'sales.delta': { en: 'change in revenue', es: 'cambio en ingresos', vi: 'thay đổi doanh thu', zh: '收入变化', fr: 'variation du CA' },

  // ── New Business Step ──
  'newbiz.title': { en: 'New Business Criteria', es: 'Criterios de negocio nuevo', vi: 'Tiêu chí doanh nghiệp mới', zh: '新企业标准', fr: 'Critères de nouvelle entreprise' },
  'newbiz.desc': { en: 'To be considered a \u201cNew Business,\u201d you must have completed required registration(s) with the local, state, and/or Federal Government (e.g., DBA registration, get a business license, agency issued tax identifications, etc.) AND at least one of the following requirements:', es: 'Para ser considerado un \u201cNuevo Negocio,\u201d debe haber completado los registros requeridos con el gobierno local, estatal y/o federal (p. ej., registro DBA, licencia comercial, identificación fiscal) Y al menos uno de los siguientes requisitos:', vi: 'Để được coi là \u201cDoanh nghiệp mới,\u201d bạn phải hoàn thành đăng ký cần thiết với chính quyền địa phương, tiểu bang và/hoặc liên bang (ví dụ: đăng ký DBA, giấy phép kinh doanh, mã số thuế) VÀ ít nhất một trong các yêu cầu sau:', zh: '要被认定为"新企业"，您必须已完成当地、州和/或联邦政府要求的注册（例如DBA注册、营业执照、税务识别号等），并且满足以下至少一项要求：', fr: 'Pour être considéré comme une \u201cNouvelle Entreprise,\u201d vous devez avoir effectué les enregistrements requis auprès des autorités locales, étatiques et/ou fédérales ET remplir au moins l\u2019un des critères suivants :' },
  'newbiz.c1': { en: 'Sold a product/provided services to customers for profit', es: 'Vendió un producto/proporcionó servicios a clientes con fines de lucro', vi: 'Đã bán sản phẩm/cung cấp dịch vụ cho khách hàng vì lợi nhuận', zh: '向客户销售产品/提供服务以盈利', fr: 'Vendu un produit/fourni des services à des clients à des fins lucratives' },
  'newbiz.c2': { en: 'You paid either yourself, employee(s) or contractor(s) to perform essential business functions', es: 'Pagó a usted mismo, empleados o contratistas para funciones esenciales del negocio', vi: 'Bạn đã trả lương cho bản thân, nhân viên hoặc nhà thầu để thực hiện các chức năng kinh doanh thiết yếu', zh: '您支付了自己、员工或承包商薪酬以执行基本业务职能', fr: 'Vous avez payé vous-même, des employés ou des sous-traitants pour des fonctions essentielles' },
  'newbiz.c3': { en: 'Invested your own money, got a loan or used a grant to purchase inventory, equipment, or pay for operations', es: 'Invirtió su propio dinero, obtuvo un préstamo o usó una subvención para comprar inventario, equipo o pagar operaciones', vi: 'Đầu tư tiền riêng, vay hoặc sử dụng tài trợ để mua hàng tồn kho, thiết bị hoặc chi trả hoạt động', zh: '投入自有资金、获得贷款或使用赠款购买库存、设备或支付运营费用', fr: 'Investi votre propre argent, obtenu un prêt ou utilisé une subvention pour acheter du stock, de l\u2019équipement ou payer les opérations' },
  'newbiz.c4': { en: 'Incurred business expenses in the operation of the business', es: 'Incurrió en gastos comerciales en la operación del negocio', vi: 'Phát sinh chi phí kinh doanh trong hoạt động kinh doanh', zh: '在企业经营中产生了业务费用', fr: 'Engagé des dépenses commerciales dans le cadre de l\u2019exploitation' },
  'newbiz.yes': { en: 'Yes, my business meets at least one of the above criteria.', es: 'Sí, mi negocio cumple al menos uno de los criterios anteriores.', vi: 'Có, doanh nghiệp của tôi đáp ứng ít nhất một tiêu chí trên.', zh: '是的，我的企业满足上述至少一项标准。', fr: 'Oui, mon entreprise remplit au moins un des critères ci-dessus.' },
  'newbiz.no': { en: 'No, my business does not yet meet any of the above criteria.', es: 'No, mi negocio aún no cumple ninguno de los criterios anteriores.', vi: 'Không, doanh nghiệp của tôi chưa đáp ứng tiêu chí nào ở trên.', zh: '不，我的企业尚未满足上述任何标准。', fr: 'Non, mon entreprise ne remplit pas encore ces critères.' },
  'newbiz.supportP1': { en: 'Thank you for updating us on your business\u2019s status. We understand that every entrepreneur\u2019s journey is different, and it\u2019s important to move forward when the time is right for you.', es: 'Gracias por actualizarnos sobre el estado de su negocio. Entendemos que el camino de cada emprendedor es diferente.', vi: 'Cảm ơn bạn đã cập nhật tình trạng doanh nghiệp. Chúng tôi hiểu rằng hành trình của mỗi doanh nhân là khác nhau.', zh: '感谢您更新您企业的状况。我们理解每个企业家的旅程都不同。', fr: 'Merci de nous avoir mis à jour sur l\u2019état de votre entreprise. Nous comprenons que chaque parcours entrepreneurial est différent.' },
  'newbiz.supportP2': { en: 'If you need help starting your business, please feel free to contact your SBDC office.', es: 'Si necesita ayuda para iniciar su negocio, contacte su oficina SBDC.', vi: 'Nếu bạn cần giúp đỡ để bắt đầu kinh doanh, hãy liên hệ văn phòng SBDC.', zh: '如果您需要帮助创办企业，请联系您的SBDC办公室。', fr: 'Si vous avez besoin d\u2019aide pour créer votre entreprise, contactez votre bureau SBDC.' },
  'newbiz.findSbdc': { en: 'Find My SBDC', es: 'Encontrar mi SBDC', vi: 'Tìm SBDC của tôi', zh: '找到我的SBDC', fr: 'Trouver mon SBDC' },
  'newbiz.supportP3': { en: 'We\u2019re here to support you as you work towards your business goals. Whenever you\u2019re ready, SBDC is here to help you take the next steps with confidence.', es: 'Estamos aquí para apoyarle mientras trabaja hacia sus metas comerciales. Cuando esté listo, el SBDC está aquí para ayudarle.', vi: 'Chúng tôi sẵn sàng hỗ trợ bạn khi bạn hướng tới mục tiêu kinh doanh. Khi bạn sẵn sàng, SBDC sẽ giúp bạn.', zh: '我们在这里支持您实现业务目标。当您准备好时，SBDC随时帮助您自信地迈出下一步。', fr: 'Nous sommes là pour vous accompagner vers vos objectifs. Quand vous serez prêt, le SBDC vous aidera.' },
  'newbiz.structureLabel': { en: 'Business Structure', es: 'Estructura empresarial', vi: 'Cơ cấu doanh nghiệp', zh: '企业结构', fr: 'Structure juridique' },
  'newbiz.dateLabel': { en: 'Business Start Date', es: 'Fecha de inicio del negocio', vi: 'Ngày bắt đầu kinh doanh', zh: '企业开业日期', fr: 'Date de création' },
  'newbiz.selectOpt': { en: 'Select Option', es: 'Seleccionar opción', vi: 'Chọn tùy chọn', zh: '选择选项', fr: 'Sélectionner' },
  'newbiz.bCorp': { en: 'B Corporation', es: 'Corporación B', vi: 'Tập đoàn B', zh: 'B型公司', fr: 'B Corporation' },
  'newbiz.cCorp': { en: 'C Corporation', es: 'Corporación C', vi: 'Tập đoàn C', zh: 'C型公司', fr: 'C Corporation' },
  'newbiz.corp': { en: 'Corporation', es: 'Corporación', vi: 'Tập đoàn', zh: '公司', fr: 'Société' },
  'newbiz.llc': { en: 'Limited Liability Co.', es: 'Sociedad de responsabilidad limitada', vi: 'Công ty TNHH', zh: '有限责任公司', fr: 'SARL' },
  'newbiz.nonprofit': { en: 'Non-profit Organization', es: 'Organización sin fines de lucro', vi: 'Tổ chức phi lợi nhuận', zh: '非营利组织', fr: 'Association à but non lucratif' },
  'newbiz.partnership': { en: 'Partnership', es: 'Sociedad', vi: 'Hợp danh', zh: '合伙企业', fr: 'Partenariat' },
  'newbiz.sole': { en: 'Sole Proprietorship', es: 'Empresa unipersonal', vi: 'Doanh nghiệp tư nhân', zh: '个体经营', fr: 'Entreprise individuelle' },
  'newbiz.sCorp': { en: 'Sub S Corporation', es: 'Corporación Sub S', vi: 'Tập đoàn Sub S', zh: 'S型公司', fr: 'Sub S Corporation' },

  // ── Funding Step ──
  'fund.title': { en: 'Business Funding', es: 'Financiamiento empresarial', vi: 'Tài trợ doanh nghiệp', zh: '企业融资', fr: 'Financement de l\u2019entreprise' },
  'fund.desc': { en: 'Tell us about any funding you\u2019ve secured for your business since your last interaction with the SBDC.', es: 'Cuéntenos sobre cualquier financiamiento que haya obtenido desde su última interacción con el SBDC.', vi: 'Hãy cho chúng tôi biết về bất kỳ khoản tài trợ nào bạn đã nhận được kể từ lần tương tác cuối với SBDC.', zh: '请告诉我们自上次与SBDC互动以来您获得的任何资金。', fr: 'Parlez-nous des financements obtenus depuis votre dernier échange avec le SBDC.' },
  'fund.ownQ': { en: 'In the last 12 months, did you invest any of your own money into your business?', es: 'En los últimos 12 meses, ¿invirtió dinero propio en su negocio?', vi: 'Trong 12 tháng qua, bạn có đầu tư tiền riêng vào doanh nghiệp không?', zh: '在过去12个月内，您是否将自有资金投入企业？', fr: 'Au cours des 12 derniers mois, avez-vous investi votre propre argent dans votre entreprise ?' },
  'fund.howMuch': { en: 'How much did you invest?', es: '¿Cuánto invirtió?', vi: 'Bạn đã đầu tư bao nhiêu?', zh: '您投资了多少？', fr: 'Combien avez-vous investi ?' },
  'fund.otherQ': { en: 'Did you receive any other funding or investments?', es: '¿Recibió algún otro financiamiento o inversión?', vi: 'Bạn có nhận được bất kỳ khoản tài trợ hoặc đầu tư nào khác không?', zh: '您是否收到了其他资金或投资？', fr: 'Avez-vous reçu d\u2019autres financements ou investissements ?' },
  'fund.addSources': { en: 'Add your funding sources below', es: 'Agregue sus fuentes de financiamiento', vi: 'Thêm nguồn tài trợ bên dưới', zh: '在下方添加您的资金来源', fr: 'Ajoutez vos sources de financement ci-dessous' },
  'fund.typeLabel': { en: 'Funding Type', es: 'Tipo de financiamiento', vi: 'Loại tài trợ', zh: '资金类型', fr: 'Type de financement' },
  'fund.amountLabel': { en: 'Total Amount', es: 'Monto total', vi: 'Tổng số tiền', zh: '总金额', fr: 'Montant total' },
  'fund.descPlaceholder': { en: 'Describe funding source', es: 'Describa la fuente de financiamiento', vi: 'Mô tả nguồn tài trợ', zh: '描述资金来源', fr: 'Décrivez la source de financement' },
  'fund.addAnother': { en: 'Add Another Source', es: 'Agregar otra fuente', vi: 'Thêm nguồn khác', zh: '添加其他来源', fr: 'Ajouter une autre source' },
  'fund.selectType': { en: 'Select type...', es: 'Seleccionar tipo...', vi: 'Chọn loại...', zh: '选择类型...', fr: 'Sélectionner le type...' },
  'fund.sbaLoan': { en: 'SBA Loan', es: 'Préstamo SBA', vi: 'Vay SBA', zh: 'SBA贷款', fr: 'Prêt SBA' },
  'fund.bankLoan': { en: 'Commercial (Bank) Loan', es: 'Préstamo bancario', vi: 'Vay ngân hàng', zh: '商业银行贷款', fr: 'Prêt bancaire' },
  'fund.microLoan': { en: 'Micro-Loan', es: 'Micropréstamo', vi: 'Vay vi mô', zh: '小额贷款', fr: 'Micro-prêt' },
  'fund.loc': { en: 'Line of Credit', es: 'Línea de crédito', vi: 'Hạn mức tín dụng', zh: '信用额度', fr: 'Ligne de crédit' },
  'fund.vc': { en: 'Venture Capital', es: 'Capital de riesgo', vi: 'Vốn đầu tư mạo hiểm', zh: '风险投资', fr: 'Capital-risque' },
  'fund.equity': { en: 'Equity Investment / Seed Funding', es: 'Inversión de capital / Financiamiento semilla', vi: 'Đầu tư vốn / Vốn hạt giống', zh: '股权投资/种子资金', fr: 'Investissement / Amorçage' },
  'fund.grants': { en: 'Grants', es: 'Subvenciones', vi: 'Tài trợ không hoàn lại', zh: '赠款', fr: 'Subventions' },
  'fund.crowd': { en: 'Crowd Funding', es: 'Financiamiento colectivo', vi: 'Gây quỹ cộng đồng', zh: '众筹', fr: 'Financement participatif' },
  'fund.equipment': { en: 'Equipment Loan or Financing', es: 'Préstamo o financiamiento de equipo', vi: 'Vay hoặc tài trợ thiết bị', zh: '设备贷款或融资', fr: 'Prêt ou financement d\u2019équipement' },
  'fund.ssbci': { en: 'SSBCI-backed Loan', es: 'Préstamo respaldado por SSBCI', vi: 'Vay được SSBCI hỗ trợ', zh: 'SSBCI支持的贷款', fr: 'Prêt soutenu par SSBCI' },
  'fund.other': { en: 'Other', es: 'Otro', vi: 'Khác', zh: '其他', fr: 'Autre' },

  // ── Testimonial Step ──
  'test.title': { en: 'Almost done!', es: '¡Casi terminamos!', vi: 'Sắp xong rồi!', zh: '即将完成！', fr: 'Presque terminé !' },
  'test.subtitle': { en: 'Share your experience working with SBDC and sign to complete your submission.', es: 'Comparta su experiencia con el SBDC y firme para completar su envío.', vi: 'Chia sẻ trải nghiệm làm việc với SBDC và ký để hoàn tất.', zh: '分享您与SBDC合作的经验并签名以完成提交。', fr: 'Partagez votre expérience avec le SBDC et signez pour finaliser.' },
  'test.feedbackLabel': { en: 'Please share your feedback/testimonial of working with SBDC', es: 'Comparta su opinión/testimonio de trabajar con el SBDC', vi: 'Vui lòng chia sẻ phản hồi/lời chứng thực về SBDC', zh: '请分享您与SBDC合作的反馈/推荐', fr: 'Partagez votre témoignage sur votre collaboration avec le SBDC' },
  'test.optional': { en: '(optional)', es: '(opcional)', vi: '(tùy chọn)', zh: '（可选）', fr: '(facultatif)' },
  'test.placeholder': { en: 'Describe how the SBDC has assisted your business...', es: 'Describa cómo el SBDC ha asistido a su negocio...', vi: 'Mô tả cách SBDC đã hỗ trợ doanh nghiệp của bạn...', zh: '描述SBDC如何帮助了您的企业...', fr: 'Décrivez comment le SBDC a aidé votre entreprise...' },
  'test.terms': { en: 'Responding to this survey means that you have benefited from working with the SBDC, and we have contributed towards your successes listed above.', es: 'Responder a esta encuesta significa que se ha beneficiado de trabajar con el SBDC y hemos contribuido a sus éxitos mencionados.', vi: 'Trả lời khảo sát này có nghĩa là bạn đã hưởng lợi từ việc làm việc với SBDC và chúng tôi đã đóng góp vào thành công của bạn.', zh: '回复此调查意味着您已从与SBDC的合作中受益，我们为您上述的成功做出了贡献。', fr: 'Répondre à ce sondage signifie que vous avez bénéficié du SBDC et que nous avons contribué à vos succès mentionnés.' },
  'test.pleaseNote': { en: 'Please Note:', es: 'Nota:', vi: 'Lưu ý:', zh: '请注意：', fr: 'Remarque :' },
  'test.sigLabel': { en: 'Signature', es: 'Firma', vi: 'Chữ ký', zh: '签名', fr: 'Signature' },
  'test.sigHint': { en: 'Please provide your full name (First, Middle, Last) indicating your acceptance to the terms shown above.', es: 'Proporcione su nombre completo indicando su aceptación de los términos anteriores.', vi: 'Vui lòng cung cấp họ tên đầy đủ để chấp nhận các điều khoản trên.', zh: '请提供您的全名以表示接受上述条款。', fr: 'Veuillez fournir votre nom complet pour accepter les conditions ci-dessus.' },
  'test.sigPlaceholder': { en: 'Full Name', es: 'Nombre completo', vi: 'Họ tên đầy đủ', zh: '全名', fr: 'Nom complet' },
  'test.submitting': { en: 'Submitting your milestones...', es: 'Enviando sus logros...', vi: 'Đang gửi các cột mốc...', zh: '正在提交您的里程碑...', fr: 'Soumission de vos jalons...' },

  // ── Result Screen ──
  'result.complete': { en: 'Submission Complete', es: 'Envío completado', vi: 'Đã gửi thành công', zh: '提交完成', fr: 'Soumission terminée' },
  'result.thanks': { en: 'Thank You. We sincerely appreciate your contribution.', es: 'Gracias. Apreciamos sinceramente su contribución.', vi: 'Cảm ơn bạn. Chúng tôi chân thành đánh giá cao sự đóng góp của bạn.', zh: '谢谢您。我们衷心感谢您的贡献。', fr: 'Merci. Nous apprécions sincèrement votre contribution.' },
  'result.shareMore': { en: 'Have another business impact to share?', es: '¿Tiene otro impacto empresarial para compartir?', vi: 'Có thêm tác động kinh doanh để chia sẻ?', zh: '还有其他业务影响要分享吗？', fr: 'Un autre impact à partager ?' },
  'result.shareDesc': { en: 'If you have another business success to share, we welcome your additional insights. Each business you contribute data for helps us further understand and showcase the collective impact of our support.', es: 'Si tiene otro éxito empresarial para compartir, agradecemos sus aportes adicionales. Cada negocio para el que contribuya datos nos ayuda a entender y mostrar el impacto colectivo.', vi: 'Nếu bạn có thêm thành công kinh doanh để chia sẻ, chúng tôi hoan nghênh. Mỗi doanh nghiệp bạn đóng góp dữ liệu giúp chúng tôi hiểu và thể hiện tác động chung.', zh: '如果您有其他业务成功要分享，我们欢迎。您提供的每项数据都帮助我们进一步了解和展示支持的集体影响。', fr: 'Si vous avez un autre succès à partager, vos contributions sont les bienvenues. Chaque donnée nous aide à comprendre l\u2019impact collectif.' },
  'result.shareBtn': { en: 'Share More', es: 'Compartir más', vi: 'Chia sẻ thêm', zh: '分享更多', fr: 'Partager plus' },
  'result.errorTitle': { en: 'Something went wrong', es: 'Algo salió mal', vi: 'Đã xảy ra lỗi', zh: '出了点问题', fr: 'Une erreur est survenue' },
  'result.errorDesc': { en: 'We were unable to submit your milestones. Please try again or contact your local SBDC for assistance.', es: 'No pudimos enviar sus logros. Intente de nuevo o contacte su SBDC local.', vi: 'Không thể gửi các cột mốc. Vui lòng thử lại hoặc liên hệ SBDC địa phương.', zh: '无法提交您的里程碑。请重试或联系当地SBDC寻求帮助。', fr: 'Impossible de soumettre vos jalons. Veuillez réessayer ou contacter votre SBDC local.' },
  'result.tryAgain': { en: 'Try Again', es: 'Intentar de nuevo', vi: 'Thử lại', zh: '重试', fr: 'Réessayer' },
  'result.deepLinkLoading': { en: 'Loading your records...', es: 'Cargando sus registros...', vi: 'Đang tải hồ sơ...', zh: '正在加载您的记录...', fr: 'Chargement de vos dossiers...' },

  // ── Footer ──
  'footer.text': { en: 'Funded in part through a Cooperative Agreement with the U.S. Small Business Administration.', es: 'Financiado en parte a través de un Acuerdo Cooperativo con la Administración de Pequeñas Empresas de EE. UU.', vi: 'Được tài trợ một phần thông qua Thỏa thuận Hợp tác với Cơ quan Quản lý Doanh nghiệp Nhỏ Hoa Kỳ.', zh: '部分资金来自与美国小企业管理局的合作协议。', fr: 'Financé en partie par un accord de coopération avec la U.S. Small Business Administration.' },
};

// ─── Context ────────────────────────────────────────────

interface LanguageContextValue {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  locale: 'en',
  setLocale: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>('en');

  const t = useCallback(
    (key: string): string => {
      const entry = T[key];
      if (!entry) return key;
      return entry[locale] || entry.en || key;
    },
    [locale],
  );

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
